author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: STARTUP

softdepend: [dynmap]

commands:
  debug:
    description: Debug Command
    usage: |
      /<command> [enable|disable] <nodeName>
  updater:
    description: Updater Command
    aliases: [update]
    usage: |
      /<command> status|check <nodeName>|all
      /<command> download|dl <nodeName>
  info:
    description: Info Command
    usage: |
      /<command> <anything>

permissions:

  ########################
  ## Global permissions ##
  ########################

  nplugins.admin:
    description: Global NPlugins suite admin
    default: op
    children:
      nplugins.user: true
      ncore.admin: true
      ncuboid.admin: true
      nenchantingegg.admin: true
      ngeneral.admin: true
      npermissions.admin: true
      nplayer.admin: true
      ntalk.admin: true
      ntheendagain.admin: true
      nworld.admin: true

  nplugins.user:
    description: Global NPlugins suite user
    default: op
    children:
      ncore.user: true
      ncuboid.user: true
      nenchantingegg.user: true
      ngeneral.user: true
      npermissions.user: true
      nplayer.user: true
      ntalk.user: true
      ntheendagain.user: true
      nworld.user: true

  #######################
  ## NCore permissions ##
  #######################

  ncore.admin:
    description: NCore plugin admin
    default: op
    children:
      ncore.user: true
      ncore.cmd.debug:
        default: op
      ncore.cmd.info.admin:
        default: op
        children: []
          # TODO Children permissions for each thing you can /info
      ncore.cmd.updater:
        default: op
      ncore.updater.notice:
        default: op

  ncore.user:
    description: NCore plugin user - useless for now
    default: op
    children: []
