author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]

softdepend: [NWorld]

commands:
  nenchantingegg:
    description: Main plugin command
    aliases: [nee]
    usage: |
      /<command> reload messages

permissions:

  nenchantingegg.admin:
    description: NEnchantingEgg plugin admin
    default: op
    children:
      nenchantingegg.user: true
      nenchantingegg.cmd.reload:
        default: op

  nenchantingegg.user:
    description: NEnchantingEgg plugin user - useless for now
    default: op
    children: []
