author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]
softdepend: [NWorld]

commands:
  npermissions:
    description: Main plugin command
    aliases: [permissions, nperms, perms, nperm, perm]
    usage: |
      /<command> reload <messages|groups|players>
  setgroup:
    description: Change the main group of a player
    aliases: [setg]
    usage: |
      /<command> <playerName|UUID>[,...] <groupName> [force]

permissions:

  npermissions.admin:
    description: NPermissions plugin admin
    default: op
    children:
      npermissions.user: true
      npermissions.cmd.reload:
        default: op
      npermissions.cmd.reload.messages:
        default: op
        children:
          npermissions.cmd.reload: true
      npermissions.cmd.reload.permissions:
        default: op
        children:
          npermissions.cmd.reload: true
      npermissions.cmd.setgroup:
        default: op

  npermissions.user:
    description: NPermissions plugin user - useless for now
    default: op
    children: []
