name: NCuboid
version: 0.4.0
description: Cuboid plugin for N plugin suite
author: Ribesg
website: http://www.ribesg.fr
main: fr.ribesg.bukkit.ncuboid.NCuboid

load: POSTWORLD

depend: [NCore]
softdepend: [NWorld]

commands:
    cuboid:
        description: General cuboid command
        aliases: [c,cubo]
        permission: ncuboid.cmd.general
        usage: |
            §c/<command> help
