author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]

commands:
  nworld:
    description: Main command
    aliases: [nw,world]
    usage: |
      /<command> [worldName]
      /<command> create <worldName> [seed] [requiredPermission] [hidden] [type]
      /<command> load|unload <worldName>
      /<command> setHidden|setPerm|setNether|setEnd <worldName> <value>
      /<command> reload messages
  spawn:
    description: Spawn command
    usage: |
      /<command> ["first"]
  setspawn:
    description: Set the spawn
    usage: |
      /<command> ["first"]
  warp:
    description: Warp to a point
    usage: |
      /<command> [warpName]
      /<command> <setHidden|setPerm> <warpName> <value>
  setwarp:
    description: Place / Move a Warp
    usage: |
      /<command> <warpName> -- Move a Warp
      /<command> <warpName> [requiredPermission] [hidden] -- Place a Warp
  delwarp:
    description: Remove a Warp
    usage: |
      /<command> <warpName>

permissions:

  nworld.admin:
    description: NWorld plugin admin
    default: false
    children:
      nworld.user: true
      nworld.cmd.world.all:
        default: false
        children:
          nworld.cmd.world: true
      nworld.cmd.world.create:
        default: false
        children:
          nworld.cmd.world: true
      nworld.cmd.world.load:
        default: false
        children:
          nworld.cmd.world: true
      nworld.cmd.world.unload:
        default: false
        children:
          nworld.cmd.world: true
      nworld.cmd.world.sethidden:
        default: false
        children:
          nworld.cmd.world: true
      nworld.cmd.world.setperm:
        default: false
        children:
          nworld.cmd.world: true
      nworld.cmd.world.setnether:
        default: false
        children:
          nworld.cmd.world: true
      nworld.cmd.world.setend:
        default: false
        children:
          nworld.cmd.world: true
      nworld.cmd.reload:
        default: false
      nworld.cmd.setspawn:
        default: false
        children:
          nworld.cmd.spawn: true
          nworld.cmd.setfirstspawn:
            default: false
            children:
              nworld.cmd.firstspawn:
                default: false
      nworld.cmd.warp.all:
        default: false
        children:
          nworld.cmd.warp: true
      nworld.cmd.warp.sethidden:
        default: false
        children:
          nworld.cmd.warp: true
      nworld.cmd.warp.setperm:
        default: false
        children:
          nworld.cmd.warp: true
      nworld.cmd.setwarp:
        default: false
      nworld.cmd.delwarp:
        default: false

  nworld.user:
    description: NWorld plugin user
    default: false
    children:
      nworld.cmd.world:
        default: false
      nworld.cmd.spawn:
        default: false
      nworld.cmd.warp:
        default: false
