author: Ribesg
main: ${project.groupId}.${project.name}
name: ${project.name}
description: ${project.description}
url: ${project.url}
version: maven-version-number

load: POSTWORLD

depend: [NCore]

commands:
  ntalk:
    description: Main plugin command
    usage: |
      /<command> reload messages
  pm:
    description: Private message
    aliases: [m,msg]
    usage: |
      /<command>
  pr:
    description: Respond to latest PM
    aliases: [r]
    usage: |
      /<command>
  nick:
    description: Nickname
    usage: |
      /<command> <realName> <nickName>

permissions:

  ntalk.admin:
    description: NTalk plugin admin
    default: op
    children:
      ntalk.user: true
      ntalk.color:
        default: op
      ntalk.cmd.reload:
        default: op
      ntalk.cmd.nick:
        default: op
      ntalk.cmd.spy:
        default: op
      ntalk.seenicks:
        default: op

  ntalk.user:
    description: NTalk plugin user
    default: op
    children:
      ntalk.cmd.pm:
        default: op
      ntalk.cmd.pr:
        default: op
